11:
	@echo ---------- Day 11
	@g++ ./day11.cpp
	@./a.exe

10:
	@echo ---------- Day 10
	@g++ ./day10.cpp
	@./a.exe

9:
	@echo ---------- Day 9
	@g++ ./day9.cpp
	@./a.exe

7: 
	@echo ---------- Day 7
	@g++ ./day7.cpp
	@./a.exe

5: 
	@echo ---------- Day 5
	@g++ ./day5.cpp
	@./a.exe

2: 
	@echo ---------- Day 2
	@g++ ./day2.cpp
	@./a.exe

tests: 2 5 7 9

clean: a.exe
	@rm -f ./a.exe
