11:
	@echo ---------- Day 11
	@echo
	@g++ ./day11.cpp
	@./a.exe
	@echo

10:
	@echo ---------- Day 10
	@echo
	@g++ ./day10.cpp
	@./a.exe
	@echo

9:
	@echo ---------- Day 9
	@echo
	@g++ ./day9.cpp
	@./a.exe
	@echo

7: 
	@echo ---------- Day 7
	@echo
	@g++ ./day7.cpp
	@./a.exe
	@echo

5: 
	@echo ---------- Day 5
	@echo
	@g++ ./day5.cpp
	@./a.exe
	@echo

2: 
	@echo ---------- Day 2
	@echo
	@g++ ./day2.cpp
	@./a.exe
	@echo

tests: 2 5 7 9

clean: a.exe
	@rm -f ./a.exe
