CC = g++

.PHONY = clean

1: day1.cpp
	@echo ---------- $@
	$(CC) $< -o ./$@.out
	./$@.out

2: day2.cpp
	@echo ---------- $@
	$(CC) $< -o ./$@.out
	./$@.out

3: day3.cpp
	@echo ---------- $@
	$(CC) $< -o ./$@.out
	./$@.out

clean: 
	rm -f ./*.out

